In [10]:
import pandas as pd
data= pd.read_excel("suruuu.xlsx")
print(data)

    Product id  bill no   selesman name  Unnamed: 3 product name  Unnamed: 5  \
0         1001     1234  suravi rakshit         NaN         cake         NaN
1         1002     1235  sayani rakshit         NaN          oil         NaN
2         1003     1236       onik pal          NaN    chocalate         NaN
3         1004     1237     debasis pal         NaN       chipes         NaN
4         1005     1238    joy chouduri         NaN       fruiti         NaN
5         1006     1239        yami roy         NaN  mango juice         NaN
6         1007     1240      surbhi roy         NaN  apple juice         NaN
7         1008     1341       polas bej         NaN         bear         NaN
8         1009     1342       plumi roy         NaN         wine         NaN
9         1010     1343        tiya sen         NaN          ata         NaN
10        1011     1344        piya sen         NaN         rice         NaN
11        1012     1345      tania sing         NaN         soap         NaN
12        1013     1346      sweta laha         NaN         jira         NaN
13        1014     1347        sima pal         NaN        mirch         NaN
14        1015     1348        riya bej         NaN       potato         NaN
15        1016     1349  oniket songram         NaN       tomato         NaN
16        1017     1350      jamini bej         NaN        vendi         NaN
17        1018     1451      gopal bera         NaN       orange         NaN
18        1019     1452       sivha sen         NaN         fish         NaN
19        1020     1453        ajoy bej         NaN         meat         NaN
20        1021     1454        anis pol         NaN         cake         NaN
21        1022     1455       tapas das         NaN          oil         NaN
22        1023     1456        pakhipol         NaN    chocalate         NaN
23        1024     1457        rasi nag         NaN       chipes         NaN
24        1025     1558        anu bera         NaN       fruiti         NaN
25        1016     1559      kobita das         NaN  mango juice         NaN
26        1027     1560      sibani sen         NaN  apple juice         NaN
27        1028     1561     animas bera         NaN         bear         NaN
28        1029     1562       onima pal         NaN         wine         NaN
29        1030     1563      sumona bag         NaN          ata         NaN
30        1031     1564       shbho roy         NaN         rice         NaN
31        1032     1565      tonima roy         NaN         soap         NaN
32        1033     1566       ishan roy         NaN         jira         NaN
33        1034     1667      oukush pal         NaN        mirch         NaN
34        1035     1668    nomita gorai         NaN       potato         NaN
35        1032     1669        puja bag         NaN       tomato         NaN
36        1037     1670     sripa gorai         NaN        vendi         NaN
37        1038     1671    swrupa gotok         NaN       orange         NaN
38        1039     1672      suravi nag         NaN         fish         NaN
39        1040     1673   sumen songram         NaN         cake         NaN
40        1041     1774      ishan gosh         NaN        onion         NaN
41        1042     1774      piyali sen         NaN    holliliks         NaN
42        1043     1774      asmina bej         NaN          oil         NaN
43        1041     1774     gontu dutta         NaN        duber         NaN
44        1045     1774       kiara roy         NaN     zandubam         NaN
45        1046     1774      kimaya sen         NaN          oil         NaN
46        1047     1880     arjun dutta         NaN       banana         NaN
47        1047     1881      devjit kor         NaN         bear         NaN
48        1049     1882    sorbojit bej         NaN         wine         NaN

     zone  seles
0   west      23
1    east     45
2   south     34
3   north     56
4   west      56
5   south     67
6   north     45
7    east     67
8   west      23
9   north     45
10  south     66
11  west      89
12   east     34
13  south     56
14  north     54
15  west      56
16   east     78
17  south     34
18  north     45
19  west      23
20   east     12
21  south     32
22   east     54
23  west      76
24  south     87
25  north     90
26  south     67
27  west      34
28   east     40
29  south     50
30  south     60
31  north     39
32  north     30
33   east     50
34   east     80
35  west      70
36  west      59
37   east     20
38  south     10
39  west      22
40  north     33
41  north     44
42  south     55
43  south     66
44  west      33
45  west      44
46   east     45
47   east     43
48  south     23

In [11]:
import pandas as pd
data=pd.read_excel("suruuu.xlsx")
print(data)

    Product id  bill no   selesman name  Unnamed: 3 product name  Unnamed: 5  \
0         1001     1234  suravi rakshit         NaN         cake         NaN
1         1002     1235  sayani rakshit         NaN          oil         NaN
2         1003     1236       onik pal          NaN    chocalate         NaN
3         1004     1237     debasis pal         NaN       chipes         NaN
4         1005     1238    joy chouduri         NaN       fruiti         NaN
5         1006     1239        yami roy         NaN  mango juice         NaN
6         1007     1240      surbhi roy         NaN  apple juice         NaN
7         1008     1341       polas bej         NaN         bear         NaN
8         1009     1342       plumi roy         NaN         wine         NaN
9         1010     1343        tiya sen         NaN          ata         NaN
10        1011     1344        piya sen         NaN         rice         NaN
11        1012     1345      tania sing         NaN         soap         NaN
12        1013     1346      sweta laha         NaN         jira         NaN
13        1014     1347        sima pal         NaN        mirch         NaN
14        1015     1348        riya bej         NaN       potato         NaN
15        1016     1349  oniket songram         NaN       tomato         NaN
16        1017     1350      jamini bej         NaN        vendi         NaN
17        1018     1451      gopal bera         NaN       orange         NaN
18        1019     1452       sivha sen         NaN         fish         NaN
19        1020     1453        ajoy bej         NaN         meat         NaN
20        1021     1454        anis pol         NaN         cake         NaN
21        1022     1455       tapas das         NaN          oil         NaN
22        1023     1456        pakhipol         NaN    chocalate         NaN
23        1024     1457        rasi nag         NaN       chipes         NaN
24        1025     1558        anu bera         NaN       fruiti         NaN
25        1016     1559      kobita das         NaN  mango juice         NaN
26        1027     1560      sibani sen         NaN  apple juice         NaN
27        1028     1561     animas bera         NaN         bear         NaN
28        1029     1562       onima pal         NaN         wine         NaN
29        1030     1563      sumona bag         NaN          ata         NaN
30        1031     1564       shbho roy         NaN         rice         NaN
31        1032     1565      tonima roy         NaN         soap         NaN
32        1033     1566       ishan roy         NaN         jira         NaN
33        1034     1667      oukush pal         NaN        mirch         NaN
34        1035     1668    nomita gorai         NaN       potato         NaN
35        1032     1669        puja bag         NaN       tomato         NaN
36        1037     1670     sripa gorai         NaN        vendi         NaN
37        1038     1671    swrupa gotok         NaN       orange         NaN
38        1039     1672      suravi nag         NaN         fish         NaN
39        1040     1673   sumen songram         NaN         cake         NaN
40        1041     1774      ishan gosh         NaN        onion         NaN
41        1042     1774      piyali sen         NaN    holliliks         NaN
42        1043     1774      asmina bej         NaN          oil         NaN
43        1041     1774     gontu dutta         NaN        duber         NaN
44        1045     1774       kiara roy         NaN     zandubam         NaN
45        1046     1774      kimaya sen         NaN          oil         NaN
46        1047     1880     arjun dutta         NaN       banana         NaN
47        1047     1881      devjit kor         NaN         bear         NaN
48        1049     1882    sorbojit bej         NaN         wine         NaN

     zone  seles
0   west      23
1    east     45
2   south     34
3   north     56
4   west      56
5   south     67
6   north     45
7    east     67
8   west      23
9   north     45
10  south     66
11  west      89
12   east     34
13  south     56
14  north     54
15  west      56
16   east     78
17  south     34
18  north     45
19  west      23
20   east     12
21  south     32
22   east     54
23  west      76
24  south     87
25  north     90
26  south     67
27  west      34
28   east     40
29  south     50
30  south     60
31  north     39
32  north     30
33   east     50
34   east     80
35  west      70
36  west      59
37   east     20
38  south     10
39  west      22
40  north     33
41  north     44
42  south     55
43  south     66
44  west      33
45  west      44
46   east     45
47   east     43
48  south     23

In [13]:
print(data.isnull())

    Product id  bill no  selesman name  Unnamed: 3  product name  Unnamed: 5  \
0        False    False          False        True         False        True
1        False    False          False        True         False        True
2        False    False          False        True         False        True
3        False    False          False        True         False        True
4        False    False          False        True         False        True
5        False    False          False        True         False        True
6        False    False          False        True         False        True
7        False    False          False        True         False        True
8        False    False          False        True         False        True
9        False    False          False        True         False        True
10       False    False          False        True         False        True
11       False    False          False        True         False        True
12       False    False          False        True         False        True
13       False    False          False        True         False        True
14       False    False          False        True         False        True
15       False    False          False        True         False        True
16       False    False          False        True         False        True
17       False    False          False        True         False        True
18       False    False          False        True         False        True
19       False    False          False        True         False        True
20       False    False          False        True         False        True
21       False    False          False        True         False        True
22       False    False          False        True         False        True
23       False    False          False        True         False        True
24       False    False          False        True         False        True
25       False    False          False        True         False        True
26       False    False          False        True         False        True
27       False    False          False        True         False        True
28       False    False          False        True         False        True
29       False    False          False        True         False        True
30       False    False          False        True         False        True
31       False    False          False        True         False        True
32       False    False          False        True         False        True
33       False    False          False        True         False        True
34       False    False          False        True         False        True
35       False    False          False        True         False        True
36       False    False          False        True         False        True
37       False    False          False        True         False        True
38       False    False          False        True         False        True
39       False    False          False        True         False        True
40       False    False          False        True         False        True
41       False    False          False        True         False        True
42       False    False          False        True         False        True
43       False    False          False        True         False        True
44       False    False          False        True         False        True
45       False    False          False        True         False        True
46       False    False          False        True         False        True
47       False    False          False        True         False        True
48       False    False          False        True         False        True

     zone  seles
0   False  False
1   False  False
2   False  False
3   False  False
4   False  False
5   False  False
6   False  False
7   False  False
8   False  False
9   False  False
10  False  False
11  False  False
12  False  False
13  False  False
14  False  False
15  False  False
16  False  False
17  False  False
18  False  False
19  False  False
20  False  False
21  False  False
22  False  False
23  False  False
24  False  False
25  False  False
26  False  False
27  False  False
28  False  False
29  False  False
30  False  False
31  False  False
32  False  False
33  False  False
34  False  False
35  False  False
36  False  False
37  False  False
38  False  False
39  False  False
40  False  False
41  False  False
42  False  False
43  False  False
44  False  False
45  False  False
46  False  False
47  False  False
48  False  False

In [14]:
data.isnull().sum()

Product id        0
bill no           0
selesman name     0
Unnamed: 3       49
product name      0
Unnamed: 5       49
zone              0
seles             0
dtype: int64

In [2]:
import pandas as pd
data=pd.read_excel("moni3.xlsx")
print(data.head(10))

  stop _data stop_time  country_name driver_name driver gender  \
0 2024-01-02   12.00am           NaN          SR             F
1 2024-01-03    1.00am           NaN          PR             M
2 2024-01-04    2.00am           NaN          MN             F
3 2024-01-05    3.00am           NaN          ER             M
4 2024-01-06    4.00am           NaN          SU             F
5 2024-01-07    5.00am           NaN          DU             M
6 2024-01-08    6.00am           NaN          DK             M
7 2024-01-09    7.00am           NaN          FK             F
8 2024-01-10    8.00am           NaN          GK             F
9 2024-01-11    9.00am           NaN          HN             M

   driver_age_raw  Unnamed: 6  driver age car color violation_raw violacation  \
0          1950.0         NaN        74.0       red      speeding    speeding
1          1941.0         NaN        83.0      blue      speeding    speeding
2          1942.0         NaN        82.0    yellow      speeding    speeding
3          1943.0         NaN        81.0      gray      speeding    speeding
4          1944.0         NaN        80.0     white      speeding    speeding
5          1945.0         NaN        79.0     white      speeding    speeding
6          1946.0         NaN        78.0     white      speeding    speeding
7          1947.0         NaN        77.0     white      speeding    speeding
8          1948.0         NaN        76.0     white      speeding    speeding
9          1949.0         NaN        75.0     white      speeding    speeding

   search_conducted
0                0.0
1                0.0
2                0.0
3                0.0
4                0.0
5                0.0
6                0.0
7                0.0
8                0.0
9                0.0

In [3]:
data.isnull()

,stop _data,stop_time,country_name,driver_name,driver gender,driver_age_raw,Unnamed: 6,driver age,car color,violation_raw,violacation,search_conducted
0,False,False,True,False,False,False,True,False,False,False,False,False
1,False,False,True,False,False,False,True,False,False,False,False,False
2,False,False,True,False,False,False,True,False,False,False,False,False
3,False,False,True,False,False,False,True,False,False,False,False,False
4,False,False,True,False,False,False,True,False,False,False,False,False
5,False,False,True,False,False,False,True,False,False,False,False,False
6,False,False,True,False,False,False,True,False,False,False,False,False
7,False,False,True,False,False,False,True,False,False,False,False,False
8,False,False,True,False,False,False,True,False,False,False,False,False
9,False,False,True,False,False,False,True,False,False,False,False,False
10,False,False,True,False,False,False,True,False,False,True,True,False
11,False,False,True,False,False,False,True,False,False,False,True,False
12,False,False,True,False,False,False,True,False,False,False,True,False
13,False,False,True,False,False,False,True,False,False,False,True,False
14,False,False,True,False,False,False,True,False,False,False,True,False
15,False,False,True,False,False,False,True,False,False,False,False,False
16,False,False,True,False,False,False,True,False,False,False,False,False
17,False,False,True,False,False,False,True,False,False,False,False,False
18,False,False,True,False,False,False,True,False,False,False,False,False
19,False,False,True,False,False,False,True,False,False,False,False,False
20,False,False,True,False,False,False,True,False,False,False,False,False
21,False,False,True,False,False,False,True,False,False,False,False,False
22,False,False,True,False,False,False,True,False,False,False,False,False
23,False,False,True,False,False,False,True,False,False,False,False,False
24,False,False,True,False,False,False,True,False,False,False,False,False
25,False,False,True,False,False,False,True,False,False,False,False,False
26,False,False,True,False,False,False,True,False,False,False,False,False
27,False,False,True,False,False,False,True,False,False,False,False,False
28,False,False,True,False,False,False,True,False,False,False,False,False
29,False,False,True,False,False,False,True,False,False,False,False,False
30,False,False,True,False,False,False,True,False,False,False,False,False
31,False,False,True,False,False,False,True,False,False,False,False,False
32,False,False,True,False,False,False,True,False,False,False,False,False
33,False,False,True,False,False,False,True,False,False,False,False,False
34,False,False,True,False,False,False,True,False,False,False,False,False
35,False,False,True,False,False,False,True,False,False,False,False,False
36,False,False,True,False,False,False,True,False,False,False,False,False
37,False,False,True,False,False,False,True,False,False,False,False,False
38,False,False,True,False,False,False,True,False,False,False,False,False
39,False,False,True,False,False,False,True,False,False,False,False,False
40,False,False,True,False,False,False,True,False,False,False,False,False
41,False,False,True,False,False,False,True,False,False,False,False,False
42,False,False,True,False,False,False,True,False,False,False,False,False
43,False,False,True,False,False,False,True,False,False,False,False,False
44,False,False,True,False,False,False,True,False,False,False,False,False
45,False,False,True,False,False,False,True,False,False,False,False,False
46,False,False,True,False,False,False,True,False,False,False,False,False
47,False,False,True,False,False,False,True,False,False,False,False,False
48,False,False,True,False,False,False,True,False,False,False,False,False
49,False,False,True,False,False,False,True,False,False,False,False,False
50,False,False,True,False,False,False,True,False,False,False,False,False
51,False,False,True,False,False,False,True,False,False,False,False,False
52,False,False,True,False,False,False,True,False,False,False,False,False
53,False,False,True,False,False,False,True,False,False,False,False,False
54,False,False,True,False,False,False,True,False,False,False,False,False
55,False,False,True,False,False,False,True,False,False,False,False,False
56,False,False,True,False,False,False,True,False,False,False,False,False
57,False,False,True,False,False,False,True,False,False,False,False,False
58,False,False,True,False,False,True,True,True,True,True,True,True

In [4]:
data.notnull()

,stop _data,stop_time,country_name,driver_name,driver gender,driver_age_raw,Unnamed: 6,driver age,car color,violation_raw,violacation,search_conducted
0,True,True,False,True,True,True,False,True,True,True,True,True
1,True,True,False,True,True,True,False,True,True,True,True,True
2,True,True,False,True,True,True,False,True,True,True,True,True
3,True,True,False,True,True,True,False,True,True,True,True,True
4,True,True,False,True,True,True,False,True,True,True,True,True
5,True,True,False,True,True,True,False,True,True,True,True,True
6,True,True,False,True,True,True,False,True,True,True,True,True
7,True,True,False,True,True,True,False,True,True,True,True,True
8,True,True,False,True,True,True,False,True,True,True,True,True
9,True,True,False,True,True,True,False,True,True,True,True,True
10,True,True,False,True,True,True,False,True,True,False,False,True
11,True,True,False,True,True,True,False,True,True,True,False,True
12,True,True,False,True,True,True,False,True,True,True,False,True
13,True,True,False,True,True,True,False,True,True,True,False,True
14,True,True,False,True,True,True,False,True,True,True,False,True
15,True,True,False,True,True,True,False,True,True,True,True,True
16,True,True,False,True,True,True,False,True,True,True,True,True
17,True,True,False,True,True,True,False,True,True,True,True,True
18,True,True,False,True,True,True,False,True,True,True,True,True
19,True,True,False,True,True,True,False,True,True,True,True,True
20,True,True,False,True,True,True,False,True,True,True,True,True
21,True,True,False,True,True,True,False,True,True,True,True,True
22,True,True,False,True,True,True,False,True,True,True,True,True
23,True,True,False,True,True,True,False,True,True,True,True,True
24,True,True,False,True,True,True,False,True,True,True,True,True
25,True,True,False,True,True,True,False,True,True,True,True,True
26,True,True,False,True,True,True,False,True,True,True,True,True
27,True,True,False,True,True,True,False,True,True,True,True,True
28,True,True,False,True,True,True,False,True,True,True,True,True
29,True,True,False,True,True,True,False,True,True,True,True,True
30,True,True,False,True,True,True,False,True,True,True,True,True
31,True,True,False,True,True,True,False,True,True,True,True,True
32,True,True,False,True,True,True,False,True,True,True,True,True
33,True,True,False,True,True,True,False,True,True,True,True,True
34,True,True,False,True,True,True,False,True,True,True,True,True
35,True,True,False,True,True,True,False,True,True,True,True,True
36,True,True,False,True,True,True,False,True,True,True,True,True
37,True,True,False,True,True,True,False,True,True,True,True,True
38,True,True,False,True,True,True,False,True,True,True,True,True
39,True,True,False,True,True,True,False,True,True,True,True,True
40,True,True,False,True,True,True,False,True,True,True,True,True
41,True,True,False,True,True,True,False,True,True,True,True,True
42,True,True,False,True,True,True,False,True,True,True,True,True
43,True,True,False,True,True,True,False,True,True,True,True,True
44,True,True,False,True,True,True,False,True,True,True,True,True
45,True,True,False,True,True,True,False,True,True,True,True,True
46,True,True,False,True,True,True,False,True,True,True,True,True
47,True,True,False,True,True,True,False,True,True,True,True,True
48,True,True,False,True,True,True,False,True,True,True,True,True
49,True,True,False,True,True,True,False,True,True,True,True,True
50,True,True,False,True,True,True,False,True,True,True,True,True
51,True,True,False,True,True,True,False,True,True,True,True,True
52,True,True,False,True,True,True,False,True,True,True,True,True
53,True,True,False,True,True,True,False,True,True,True,True,True
54,True,True,False,True,True,True,False,True,True,True,True,True
55,True,True,False,True,True,True,False,True,True,True,True,True
56,True,True,False,True,True,True,False,True,True,True,True,True
57,True,True,False,True,True,True,False,True,True,True,True,True
58,True,True,False,True,True,False,False,False,False,False,False,False

In [3]:
import pandas as pd
data=pd.read_excel("moni3.xlsx")
print(data)

   stop _data stop_time  country_name driver_name driver gender  \
0  2024-01-02   12.00am           NaN          SR             F
1  2024-01-03    1.00am           NaN          PR             M
2  2024-01-04    2.00am           NaN          MN             F
3  2024-01-05    3.00am           NaN          ER             M
4  2024-01-06    4.00am           NaN          SU             F
5  2024-01-07    5.00am           NaN          DU             M
6  2024-01-08    6.00am           NaN          DK             M
7  2024-01-09    7.00am           NaN          FK             F
8  2024-01-10    8.00am           NaN          GK             F
9  2024-01-11    9.00am           NaN          HN             M
10 2024-01-12   10.00am           NaN          JK             M
11 2024-01-13   11.00am           NaN          LK             F
12 2024-01-14   12.00pm           NaN          GH             M
13 2024-01-15    1.00pm           NaN          BN             F
14 2024-01-16    2.00pm           NaN          FB             M
15 2024-01-17    3.00pm           NaN          DB             F
16 2024-01-18    4.00pm           NaN          SV             M
17 2024-01-19    5.00pm           NaN          DN             F
18 2024-01-20    6.00pm           NaN          FV             F
19 2024-01-21    7.00pm           NaN          GO             M
20 2024-01-22    8.00pm           NaN          YP             M
21 2024-01-23    9.00pm           NaN          UO             F
22 2024-01-24   10.00pm           NaN          IK             M
23 2024-01-25   11.00pm           NaN          DM             F
24 2024-01-26   12.00am           NaN          SN             M
25 2024-01-27    1.00am           NaN          EK             F
26 2024-01-28    2.00am           NaN          RN             F
27 2024-01-29    3.00am           NaN          SM             F
28 2024-01-30    4.00am           NaN          DF             F
29 2024-01-31    5.00am           NaN          SD             F
30 2024-02-01    6.00am           NaN          AD             M
31 2024-02-02    7.00am           NaN          XD             M
32 2024-02-03    8.00am           NaN          ZO             M
33 2024-02-04    9.00am           NaN          WP             M
34 2024-02-05   10.00am           NaN          IM             M
35 2024-02-06   11.00am           NaN          DL             M
36 2024-02-07   12.00pm           NaN          SK             M
37 2024-02-08   12.00pm           NaN          AK             M
38 2024-02-09    1.00pm           NaN          SL             M
39 2024-02-10    2.00pm           NaN          DK             M
40 2024-02-11    3.00pm           NaN          DF             M
41 2024-02-12    4.00pm           NaN          GH             M
42 2024-02-13    5.00pm           NaN          HO             M
43 2024-02-14    6.00pm           NaN          RT             F
44 2024-02-15    7.00pm           NaN          ET             F
45 2024-02-16    8.00pm           NaN          WE             F
46 2024-02-17    9.00pm           NaN          TU             F
47 2024-02-18   10.00pm           NaN          UI             F
48 2024-02-19   11.00pm           NaN          OP             F
49 2024-02-20   12.00am           NaN          YH             M
50 2024-02-21    1.00am           NaN          TG             M
51 2024-02-22    2.00am           NaN          RF             M
52 2024-02-23    3.00am           NaN          ED             M
53 2024-02-24    4.00am           NaN          WS             M
54 2024-02-25    5.00am           NaN          AQ             M
55 2024-02-26    6.00am           NaN         ZCB             M
56 2024-02-27    7.00am           NaN          MD           NAN
57 2024-02-28    8.00am           NaN          CO             F
58 2024-02-29    9.00am           NaN          PR             M

    driver_age_raw  Unnamed: 6  driver age car color     violation_raw  \
0           1950.0         NaN        74.0       red          speeding
1           1941.0         NaN        83.0      blue          speeding
2           1942.0         NaN        82.0    yellow          speeding
3           1943.0         NaN        81.0      gray          speeding
4           1944.0         NaN        80.0     white          speeding
5           1945.0         NaN        79.0     white          speeding
6           1946.0         NaN        78.0     white          speeding
7           1947.0         NaN        77.0     white          speeding
8           1948.0         NaN        76.0     white          speeding
9           1949.0         NaN        75.0     white          speeding
10          1950.0         NaN        74.0     white               NaN
11          1951.0         NaN        73.0     white          speeding
12          1952.0         NaN        72.0     white          speeding
13          1953.0         NaN        71.0     white          speeding
14          1954.0         NaN        70.0     white          speeding
15          1955.0         NaN        69.0     white          speeding
16          1956.0         NaN        68.0     white          speeding
17          1957.0         NaN        67.0     white          speeding
18          1958.0         NaN        66.0     white          speeding
19          1959.0         NaN        65.0     white          speeding
20          1960.0         NaN        64.0     white          speeding
21          1961.0         NaN        63.0     white          speeding
22          1962.0         NaN        62.0     white          speeding
23          1963.0         NaN        61.0     white          speeding
24          1964.0         NaN        60.0     white          speeding
25          1965.0         NaN        59.0     white          speeding
26          1966.0         NaN        58.0     white          speeding
27          1967.0         NaN        57.0      blue          speeding
28          1968.0         NaN        56.0      blue          speeding
29          1969.0         NaN        55.0      blue          speeding
30          1970.0         NaN        54.0      blue          speeding
31          1971.0         NaN        53.0      blue          speeding
32          1972.0         NaN        52.0      blue          speeding
33          1973.0         NaN        51.0      blue          speeding
34          1974.0         NaN        50.0      blue          speeding
35          1975.0         NaN        49.0      blue          speeding
36          1976.0         NaN        48.0      blue          speeding
37          1977.0         NaN        47.0      blue          speeding
38          1978.0         NaN        46.0      blue          speeding
39          1979.0         NaN        45.0      blue          speeding
40          1980.0         NaN        44.0      blue          speeding
41          1981.0         NaN        43.0      blue          speeding
42          1982.0         NaN        42.0      blue          speeding
43          1983.0         NaN        41.0      blue          speeding
44          1984.0         NaN        40.0      blue  call the service
45          1985.0         NaN        39.0      blue          speeding
46          1986.0         NaN        38.0      blue          speeding
47          1987.0         NaN        37.0      blue          speeding
48          1988.0         NaN        36.0      blue          speeding
49          1989.0         NaN        35.0      blue          speeding
50          1990.0         NaN        34.0      blue          speeding
51          1991.0         NaN        33.0      blue          speeding
52          1992.0         NaN        32.0       red          speeding
53          1993.0         NaN        31.0       red          speeding
54          1994.0         NaN        30.0       red          speeding
55          1995.0         NaN        29.0       red          speeding
56          1996.0         NaN        28.0       red          speeding
57          1997.0         NaN        27.0       red          speeding
58             NaN         NaN         NaN       NaN               NaN

   violacation  search_conducted
0     speeding                0.0
1     speeding                0.0
2     speeding                0.0
3     speeding                0.0
4     speeding                0.0
5     speeding                0.0
6     speeding                0.0
7     speeding                0.0
8     speeding                0.0
9     speeding                0.0
10         NaN                0.0
11         NaN                0.0
12         NaN                0.0
13         NaN                0.0
14         NaN                0.0
15    speeding                0.0
16    speeding                0.0
17    speeding                0.0
18    speeding                0.0
19    speeding                0.0
20    speeding                0.0
21    speeding                0.0
22    speeding                0.0
23    speeding                0.0
24    speeding                0.0
25    speeding                0.0
26    speeding                0.0
27    speeding                0.0
28    speeding                0.0
29    speeding                0.0
30    speeding                0.0
31    speeding                0.0
32    speeding                0.0
33    speeding                0.0
34   equirment                0.0
35   equirment                0.0
36    speeding                0.0
37    speeding                0.0
38    speeding                0.0
39    speeding                0.0
40    speeding                0.0
41    speeding                0.0
42    speeding                0.0
43    speeding                0.0
44    speeding                0.0
45    speeding                0.0
46    speeding                0.0
47    speeding                0.0
48    speeding                0.0
49    speeding                0.0
50   equirment                0.0
51    speeding                0.0
52    speeding                0.0
53    speeding                0.0
54    speeding                0.0
55    speeding                0.0
56    speeding                0.0
57    speeding                0.0
58         NaN                NaN

In [4]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   stop _data         59 non-null     datetime64[ns]
 1   stop_time          59 non-null     object
 2   country_name       0 non-null      float64
 3   driver_name        59 non-null     object
 4   driver gender      59 non-null     object
 5   driver_age_raw     58 non-null     float64
 6   Unnamed: 6         0 non-null      float64
 7   driver age         58 non-null     float64
 8   car color          58 non-null     object
 9   violation_raw      57 non-null     object
 10  violacation        53 non-null     object
 11  search_conducted   58 non-null     float64
dtypes: datetime64[ns](1), float64(5), object(6)
memory usage: 5.7+ KB
None

In [6]:
print(data.describe())

                stop _data  country_name  driver_age_raw  Unnamed: 6  \
count                   59           0.0       58.000000         0.0
mean   2024-01-31 00:00:00           NaN     1968.672414         NaN
min    2024-01-02 00:00:00           NaN     1941.000000         NaN
25%    2024-01-16 12:00:00           NaN     1954.250000         NaN
50%    2024-01-31 00:00:00           NaN     1968.500000         NaN
75%    2024-02-14 12:00:00           NaN     1982.750000         NaN
max    2024-02-29 00:00:00           NaN     1997.000000         NaN
std                    NaN           NaN       16.640036         NaN

       driver age  search_conducted
count   58.000000               58.0
mean    55.327586                0.0
min     27.000000                0.0
25%     41.250000                0.0
50%     55.500000                0.0
75%     69.750000                0.0
max     83.000000                0.0
std     16.640036                0.0

In [8]:
print(data.duplicated())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
52    False
53    False
54    False
55    False
56    False
57    False
58    False
dtype: bool

In [12]:
print(data.drop_duplicates("driver gender"))

   stop _data stop_time  country_name driver_name driver gender  \
0  2024-01-02   12.00am           NaN          SR             F
1  2024-01-03    1.00am           NaN          PR             M
56 2024-02-27    7.00am           NaN          MD           NAN

    driver_age_raw  Unnamed: 6  driver age car color violation_raw  \
0           1950.0         NaN        74.0       red      speeding
1           1941.0         NaN        83.0      blue      speeding
56          1996.0         NaN        28.0       red      speeding

   violacation  search_conducted
0     speeding                0.0
1     speeding                0.0
56    speeding                0.0

In [4]:
import pandas as pd
data=pd.read_excel("moni3.xlsx")
print(data)
(data.guorpby('driver gender'))

   stop _data stop_time  country_name driver_name driver gender  \
0  2024-01-02   12.00am           NaN          SR             F
1  2024-01-03    1.00am           NaN          PR             M
2  2024-01-04    2.00am           NaN          MN             F
3  2024-01-05    3.00am           NaN          ER             M
4  2024-01-06    4.00am           NaN          SU             F
5  2024-01-07    5.00am           NaN          DU             M
6  2024-01-08    6.00am           NaN          DK             M
7  2024-01-09    7.00am           NaN          FK             F
8  2024-01-10    8.00am           NaN          GK             F
9  2024-01-11    9.00am           NaN          HN             M
10 2024-01-12   10.00am           NaN          JK             M
11 2024-01-13   11.00am           NaN          LK             F
12 2024-01-14   12.00pm           NaN          GH             M
13 2024-01-15    1.00pm           NaN          BN             F
14 2024-01-16    2.00pm           NaN          FB             M
15 2024-01-17    3.00pm           NaN          DB             F
16 2024-01-18    4.00pm           NaN          SV             M
17 2024-01-19    5.00pm           NaN          DN             F
18 2024-01-20    6.00pm           NaN          FV             F
19 2024-01-21    7.00pm           NaN          GO             M
20 2024-01-22    8.00pm           NaN          YP             M
21 2024-01-23    9.00pm           NaN          UO             F
22 2024-01-24   10.00pm           NaN          IK             M
23 2024-01-25   11.00pm           NaN          DM             F
24 2024-01-26   12.00am           NaN          SN             M
25 2024-01-27    1.00am           NaN          EK             F
26 2024-01-28    2.00am           NaN          RN             F
27 2024-01-29    3.00am           NaN          SM             F
28 2024-01-30    4.00am           NaN          DF             F
29 2024-01-31    5.00am           NaN          SD             F
30 2024-02-01    6.00am           NaN          AD             M
31 2024-02-02    7.00am           NaN          XD             M
32 2024-02-03    8.00am           NaN          ZO             M
33 2024-02-04    9.00am           NaN          WP             M
34 2024-02-05   10.00am           NaN          IM             M
35 2024-02-06   11.00am           NaN          DL             M
36 2024-02-07   12.00pm           NaN          SK             M
37 2024-02-08   12.00pm           NaN          AK             M
38 2024-02-09    1.00pm           NaN          SL             M
39 2024-02-10    2.00pm           NaN          DK             M
40 2024-02-11    3.00pm           NaN          DF             M
41 2024-02-12    4.00pm           NaN          GH             M
42 2024-02-13    5.00pm           NaN          HO             M
43 2024-02-14    6.00pm           NaN          RT             F
44 2024-02-15    7.00pm           NaN          ET             F
45 2024-02-16    8.00pm           NaN          WE             F
46 2024-02-17    9.00pm           NaN          TU             F
47 2024-02-18   10.00pm           NaN          UI             F
48 2024-02-19   11.00pm           NaN          OP             F
49 2024-02-20   12.00am           NaN          YH             M
50 2024-02-21    1.00am           NaN          TG             M
51 2024-02-22    2.00am           NaN          RF             M
52 2024-02-23    3.00am           NaN          ED             M
53 2024-02-24    4.00am           NaN          WS             M
54 2024-02-25    5.00am           NaN          AQ             M
55 2024-02-26    6.00am           NaN         ZCB             M
56 2024-02-27    7.00am           NaN          MD           NAN
57 2024-02-28    8.00am           NaN          CO             F
58 2024-02-29    9.00am           NaN          PR             M

    driver_age_raw  Unnamed: 6  driver age car color     violation_raw  \
0           1950.0         NaN        74.0       red          speeding
1           1941.0         NaN        83.0      blue          speeding
2           1942.0         NaN        82.0    yellow          speeding
3           1943.0         NaN        81.0      gray          speeding
4           1944.0         NaN        80.0     white          speeding
5           1945.0         NaN        79.0     white          speeding
6           1946.0         NaN        78.0     white          speeding
7           1947.0         NaN        77.0     white          speeding
8           1948.0         NaN        76.0     white          speeding
9           1949.0         NaN        75.0     white          speeding
10          1950.0         NaN        74.0     white               NaN
11          1951.0         NaN        73.0     white          speeding
12          1952.0         NaN        72.0     white          speeding
13          1953.0         NaN        71.0     white          speeding
14          1954.0         NaN        70.0     white          speeding
15          1955.0         NaN        69.0     white          speeding
16          1956.0         NaN        68.0     white          speeding
17          1957.0         NaN        67.0     white          speeding
18          1958.0         NaN        66.0     white          speeding
19          1959.0         NaN        65.0     white          speeding
20          1960.0         NaN        64.0     white          speeding
21          1961.0         NaN        63.0     white          speeding
22          1962.0         NaN        62.0     white          speeding
23          1963.0         NaN        61.0     white          speeding
24          1964.0         NaN        60.0     white          speeding
25          1965.0         NaN        59.0     white          speeding
26          1966.0         NaN        58.0     white          speeding
27          1967.0         NaN        57.0      blue          speeding
28          1968.0         NaN        56.0      blue          speeding
29          1969.0         NaN        55.0      blue          speeding
30          1970.0         NaN        54.0      blue          speeding
31          1971.0         NaN        53.0      blue          speeding
32          1972.0         NaN        52.0      blue          speeding
33          1973.0         NaN        51.0      blue          speeding
34          1974.0         NaN        50.0      blue          speeding
35          1975.0         NaN        49.0      blue          speeding
36          1976.0         NaN        48.0      blue          speeding
37          1977.0         NaN        47.0      blue          speeding
38          1978.0         NaN        46.0      blue          speeding
39          1979.0         NaN        45.0      blue          speeding
40          1980.0         NaN        44.0      blue          speeding
41          1981.0         NaN        43.0      blue          speeding
42          1982.0         NaN        42.0      blue          speeding
43          1983.0         NaN        41.0      blue          speeding
44          1984.0         NaN        40.0      blue  call the service
45          1985.0         NaN        39.0      blue          speeding
46          1986.0         NaN        38.0      blue          speeding
47          1987.0         NaN        37.0      blue          speeding
48          1988.0         NaN        36.0      blue          speeding
49          1989.0         NaN        35.0      blue          speeding
50          1990.0         NaN        34.0      blue          speeding
51          1991.0         NaN        33.0      blue          speeding
52          1992.0         NaN        32.0       red          speeding
53          1993.0         NaN        31.0       red          speeding
54          1994.0         NaN        30.0       red          speeding
55          1995.0         NaN        29.0       red          speeding
56          1996.0         NaN        28.0       red          speeding
57          1997.0         NaN        27.0       red          speeding
58             NaN         NaN         NaN       NaN               NaN

   violacation  search_conducted
0     speeding                0.0
1     speeding                0.0
2     speeding                0.0
3     speeding                0.0
4     speeding                0.0
5     speeding                0.0
6     speeding                0.0
7     speeding                0.0
8     speeding                0.0
9     speeding                0.0
10         NaN                0.0
11         NaN                0.0
12         NaN                0.0
13         NaN                0.0
14         NaN                0.0
15    speeding                0.0
16    speeding                0.0
17    speeding                0.0
18    speeding                0.0
19    speeding                0.0
20    speeding                0.0
21    speeding                0.0
22    speeding                0.0
23    speeding                0.0
24    speeding                0.0
25    speeding                0.0
26    speeding                0.0
27    speeding                0.0
28    speeding                0.0
29    speeding                0.0
30    speeding                0.0
31    speeding                0.0
32    speeding                0.0
33    speeding                0.0
34   equirment                0.0
35   equirment                0.0
36    speeding                0.0
37    speeding                0.0
38    speeding                0.0
39    speeding                0.0
40    speeding                0.0
41    speeding                0.0
42    speeding                0.0
43    speeding                0.0
44    speeding                0.0
45    speeding                0.0
46    speeding                0.0
47    speeding                0.0
48    speeding                0.0
49    speeding                0.0
50   equirment                0.0
51    speeding                0.0
52    speeding                0.0
53    speeding                0.0
54    speeding                0.0
55    speeding                0.0
56    speeding                0.0
57    speeding                0.0
58         NaN                NaN

AttributeError: 'DataFrame' object has no attribute 'guorpby'

In [3]:
import  pandas as pd
import matplotlib.pyplot as plt
data=pd.read_excel("moni3.xlsx")
df=pd.DataFrame(data)
print(data)

   stop _data stop_time  country_name driver_name driver gender  \
0  2024-01-02   12.00am           NaN          SR             F
1  2024-01-03    1.00am           NaN          PR             M
2  2024-01-04    2.00am           NaN          MN             F
3  2024-01-05    3.00am           NaN          ER             M
4  2024-01-06    4.00am           NaN          SU             F
5  2024-01-07    5.00am           NaN          DU             M
6  2024-01-08    6.00am           NaN          DK             M
7  2024-01-09    7.00am           NaN          FK             F
8  2024-01-10    8.00am           NaN          GK             F
9  2024-01-11    9.00am           NaN          HN             M
10 2024-01-12   10.00am           NaN          JK             M
11 2024-01-13   11.00am           NaN          LK             F
12 2024-01-14   12.00pm           NaN          GH             M
13 2024-01-15    1.00pm           NaN          BN             F
14 2024-01-16    2.00pm           NaN          FB             M
15 2024-01-17    3.00pm           NaN          DB             F
16 2024-01-18    4.00pm           NaN          SV             M
17 2024-01-19    5.00pm           NaN          DN             F
18 2024-01-20    6.00pm           NaN          FV             F
19 2024-01-21    7.00pm           NaN          GO             M
20 2024-01-22    8.00pm           NaN          YP             M
21 2024-01-23    9.00pm           NaN          UO             F
22 2024-01-24   10.00pm           NaN          IK             M
23 2024-01-25   11.00pm           NaN          DM             F
24 2024-01-26   12.00am           NaN          SN             M
25 2024-01-27    1.00am           NaN          EK             F
26 2024-01-28    2.00am           NaN          RN             F
27 2024-01-29    3.00am           NaN          SM             F
28 2024-01-30    4.00am           NaN          DF             F
29 2024-01-31    5.00am           NaN          SD             F
30 2024-02-01    6.00am           NaN          AD             M
31 2024-02-02    7.00am           NaN          XD             M
32 2024-02-03    8.00am           NaN          ZO             M
33 2024-02-04    9.00am           NaN          WP             M
34 2024-02-05   10.00am           NaN          IM             M
35 2024-02-06   11.00am           NaN          DL             M
36 2024-02-07   12.00pm           NaN          SK             M
37 2024-02-08   12.00pm           NaN          AK             M
38 2024-02-09    1.00pm           NaN          SL             M
39 2024-02-10    2.00pm           NaN          DK             M
40 2024-02-11    3.00pm           NaN          DF             M
41 2024-02-12    4.00pm           NaN          GH             M
42 2024-02-13    5.00pm           NaN          HO             M
43 2024-02-14    6.00pm           NaN          RT             F
44 2024-02-15    7.00pm           NaN          ET             F
45 2024-02-16    8.00pm           NaN          WE             F
46 2024-02-17    9.00pm           NaN          TU             F
47 2024-02-18   10.00pm           NaN          UI             F
48 2024-02-19   11.00pm           NaN          OP             F
49 2024-02-20   12.00am           NaN          YH             M
50 2024-02-21    1.00am           NaN          TG             M
51 2024-02-22    2.00am           NaN          RF             M
52 2024-02-23    3.00am           NaN          ED             M
53 2024-02-24    4.00am           NaN          WS             M
54 2024-02-25    5.00am           NaN          AQ             M
55 2024-02-26    6.00am           NaN         ZCB             M
56 2024-02-27    7.00am           NaN          MD           NAN
57 2024-02-28    8.00am           NaN          CO             F
58 2024-02-29    9.00am           NaN          PR             M

    driver_age_raw  Unnamed: 6  driver age car color     violation_raw  \
0           1950.0         NaN        74.0       red          speeding
1           1941.0         NaN        83.0      blue          speeding
2           1942.0         NaN        82.0    yellow          speeding
3           1943.0         NaN        81.0      gray          speeding
4           1944.0         NaN        80.0     white          speeding
5           1945.0         NaN        79.0     white          speeding
6           1946.0         NaN        78.0     white          speeding
7           1947.0         NaN        77.0     white          speeding
8           1948.0         NaN        76.0     white          speeding
9           1949.0         NaN        75.0     white          speeding
10          1950.0         NaN        74.0     white               NaN
11          1951.0         NaN        73.0     white          speeding
12          1952.0         NaN        72.0     white          speeding
13          1953.0         NaN        71.0     white          speeding
14          1954.0         NaN        70.0     white          speeding
15          1955.0         NaN        69.0     white          speeding
16          1956.0         NaN        68.0     white          speeding
17          1957.0         NaN        67.0     white          speeding
18          1958.0         NaN        66.0     white          speeding
19          1959.0         NaN        65.0     white          speeding
20          1960.0         NaN        64.0     white          speeding
21          1961.0         NaN        63.0     white          speeding
22          1962.0         NaN        62.0     white          speeding
23          1963.0         NaN        61.0     white          speeding
24          1964.0         NaN        60.0     white          speeding
25          1965.0         NaN        59.0     white          speeding
26          1966.0         NaN        58.0     white          speeding
27          1967.0         NaN        57.0      blue          speeding
28          1968.0         NaN        56.0      blue          speeding
29          1969.0         NaN        55.0      blue          speeding
30          1970.0         NaN        54.0      blue          speeding
31          1971.0         NaN        53.0      blue          speeding
32          1972.0         NaN        52.0      blue          speeding
33          1973.0         NaN        51.0      blue          speeding
34          1974.0         NaN        50.0      blue          speeding
35          1975.0         NaN        49.0      blue          speeding
36          1976.0         NaN        48.0      blue          speeding
37          1977.0         NaN        47.0      blue          speeding
38          1978.0         NaN        46.0      blue          speeding
39          1979.0         NaN        45.0      blue          speeding
40          1980.0         NaN        44.0      blue          speeding
41          1981.0         NaN        43.0      blue          speeding
42          1982.0         NaN        42.0      blue          speeding
43          1983.0         NaN        41.0      blue          speeding
44          1984.0         NaN        40.0      blue  call the service
45          1985.0         NaN        39.0      blue          speeding
46          1986.0         NaN        38.0      blue          speeding
47          1987.0         NaN        37.0      blue          speeding
48          1988.0         NaN        36.0      blue          speeding
49          1989.0         NaN        35.0      blue          speeding
50          1990.0         NaN        34.0      blue          speeding
51          1991.0         NaN        33.0      blue          speeding
52          1992.0         NaN        32.0       red          speeding
53          1993.0         NaN        31.0       red          speeding
54          1994.0         NaN        30.0       red          speeding
55          1995.0         NaN        29.0       red          speeding
56          1996.0         NaN        28.0       red          speeding
57          1997.0         NaN        27.0       red          speeding
58             NaN         NaN         NaN       NaN               NaN

   violacation  search_conducted
0     speeding                0.0
1     speeding                0.0
2     speeding                0.0
3     speeding                0.0
4     speeding                0.0
5     speeding                0.0
6     speeding                0.0
7     speeding                0.0
8     speeding                0.0
9     speeding                0.0
10         NaN                0.0
11         NaN                0.0
12         NaN                0.0
13         NaN                0.0
14         NaN                0.0
15    speeding                0.0
16    speeding                0.0
17    speeding                0.0
18    speeding                0.0
19    speeding                0.0
20    speeding                0.0
21    speeding                0.0
22    speeding                0.0
23    speeding                0.0
24    speeding                0.0
25    speeding                0.0
26    speeding                0.0
27    speeding                0.0
28    speeding                0.0
29    speeding                0.0
30    speeding                0.0
31    speeding                0.0
32    speeding                0.0
33    speeding                0.0
34   equirment                0.0
35   equirment                0.0
36    speeding                0.0
37    speeding                0.0
38    speeding                0.0
39    speeding                0.0
40    speeding                0.0
41    speeding                0.0
42    speeding                0.0
43    speeding                0.0
44    speeding                0.0
45    speeding                0.0
46    speeding                0.0
47    speeding                0.0
48    speeding                0.0
49    speeding                0.0
50   equirment                0.0
51    speeding                0.0
52    speeding                0.0
53    speeding                0.0
54    speeding                0.0
55    speeding                0.0
56    speeding                0.0
57    speeding                0.0
58         NaN                NaN